version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: netology
      MYSQL_PASSWORD: mysql123

    ports:
      - "3306:3306"

  app:
    image: app:latest
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/netology?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql